E_commerce/E_commerce/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public int CategoryID { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
    }
}

E_commerce/E_commerce/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_commerce.Models;

namespace E_commerce.Controllers
{
    public class CartItemsController : Controller
    {
        private E_commerceEntities db = new E_commerceEntities();

        // GET: CartItems
        public ActionResult Index()
        {
            var cartItems = db.CartItems.Include(c => c.Cart).Include(c => c.Product);
            return View(cartItems.ToList());
        }

        public ActionResult Cart(int? id)
        {
          

            // الحصول على السلة والعناصر المرتبطة بها
            var cartItems = db.Carts
                              .Where(c => c.UserID == id)
                              .SelectMany(c => c.CartItems)
                              .Include(ci => ci.Product) // جلب تفاصيل المنتج
                              .ToList();

            return View(cartItems);
        }

        public ActionResult Create(int id , int userID)
        {

            // افترض أنك تحصل على UserID من الجلسة أو من مصدر آخر
            int userId = userID; // وضع الكود المناسب للحصول على UserID للمستخدم الحالي

            // تحقق مما إذا كان المستخدم يمتلك سلة بالفعل
            var cart = db.Carts.SingleOrDefault(c => c.UserID == userId);

            // إذا لم يكن لديه سلة، أنشئ واحدة جديدة
            if (cart == null)
            {
                cart = new Cart
                {
                    UserID = userId
                };
                db.Carts.Add(cart);
                db.SaveChanges(); // حفظ السلة الجديدة
            }

            // تحقق مما إذا كان العنصر موجود بالفعل في السلة
            var existingCartItem = db.CartItems
                                     .SingleOrDefault(ci => ci.CartID == cart.CartID && ci.ProductID == id);

            if (existingCartItem != null)
            {
                // إذا كان العنصر موجوداً بالفعل، قم بزيادة الكمية
                existingCartItem.Quantity++;
            }
            else
            {
                // إذا كان العنصر غير موجود في السلة، قم بإضافته
                var cartItem = new CartItem
                {
                    CartID = cart.CartID,
                    ProductID = id,
                    Quantity = 1 // تبدأ الكمية من 1
                };
                db.CartItems.Add(cartItem);
            }

            db.SaveChanges(); // حفظ التغييرات

            // إعادة التوجيه إلى صفحة السلة أو البقاء في نفس الصفحة
            return RedirectToAction("Shop", "Products");
        }

        public ActionResult UpdateQuantity(int id, int quantity)
        {
            var cartItem = db.CartItems.Find(id);

            if (cartItem != null && quantity > 0)
            {
                cartItem.Quantity = quantity;
                db.SaveChanges();
            }
            else if (cartItem != null && quantity == 0)
            {
                db.CartItems.Remove(cartItem);
                db.SaveChanges();
            }

            return RedirectToAction("Cart", new { id = Session["UserID"] /*cartItem.Cart.UserID*/ });
        }

        public ActionResult Remove(int id)
        {
            var cartItem = db.CartItems.Find(id);

            if (cartItem != null)
            {
                db.CartItems.Remove(cartItem);
                db.SaveChanges();
            }

            return RedirectToAction("Cart", new { id = Session["UserID"] /*cartItem.Cart.UserID*/ });
        }


     /// <summary>
     /// ///////////////////////////
     /// </summary>
     /// <param name="id"></param>
     /// <returns></returns>

        // GET: CartItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        //public ActionResult Create()
        //{
        //    ViewBag.CartID = new SelectList(db.Carts, "CartID", "CartID");
        //    ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName");
        //    return View();
        //}

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "CartItemID,CartID,ProductID,Quantity")] CartItem cartItem)
        //{


        //    if (ModelState.IsValid)
        //    {
        //        db.CartItems.Add(cartItem);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.CartID = new SelectList(db.Carts, "CartID", "CartID", cartItem.CartID);
        //    ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductID);
        //    return View(cartItem);
        //}




        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.CartID = new SelectList(db.Carts, "CartID", "CartID", cartItem.CartID);
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductID);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CartItemID,CartID,ProductID,Quantity")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CartID = new SelectList(db.Carts, "CartID", "CartID", cartItem.CartID);
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductID);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_commerce/E_commerce/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_commerce.Models;

namespace E_commerce.Controllers
{
    public class ProductsController : Controller
    {
        private E_commerceEntities db = new E_commerceEntities();

        // GET: Products
        public ActionResult Shop(int? id)
        {
            var products = db.Products.Include(p => p.Category);

            if (id.HasValue)
            {
                products = products.Where(p => p.CategoryID == id.Value);
            }

            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,Description,Price,Quantity,CategoryID,Image")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,Description,Price,Quantity,CategoryID,Image")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_commerce/E_commerce/Views/Products/Create.cshtml
@model E_commerce.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_EStart.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E_commerce/E_commerce/Views/Products/Delete.cshtml
@model E_commerce.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_EStart.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E_commerce/E_commerce/Views/Products/Details.cshtml
@model E_commerce.Models.Product

@{
    ViewBag.Title = "Product Details";
    Layout = "~/Views/Shared/_EStart.cshtml";
}

<h2 class="text-center">@Model.ProductName Details</h2>

<div class="card mb-4 shadow-sm">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="@Url.Content(Model.Image)" class="card-img" alt="@Model.ProductName">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h3 class="card-title">@Model.ProductName</h3>
                <p class="card-text"><strong>Description: </strong>@Model.Description</p>
                <p class="card-text"><strong>Price: </strong>@Model.Price $</p>
                <p class="card-text"><strong>Quantity: </strong>@Model.Quantity</p>
                <p class="card-text"><strong>Category: </strong>@Model.Category.CategoryName</p>
                <div class="text-right">
                    @if (Session["name"] == "0")
                    {

                        @Html.ActionLink("Add To Cart", "Create", "CartItems", new { id = Model.ProductID, userId = Session["UserID"] }, new { @class = "btn btn-primary mr-2" })
                    }
                        @Html.ActionLink("Back ", "Shop", "Products", new { @class = "btn btn-secondary" })
                    </div>
            </div>
        </div>
    </div>
</div>
<style>
    .card-img {
        height: 60vh;
        padding-left: 30%;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
        
    }
</style>

E_commerce/E_commerce/Views/Products/Edit.cshtml
@model E_commerce.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_EStart.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E_commerce/E_commerce/Views/Products/Shop.cshtml
@model IEnumerable<E_commerce.Models.Product>

@{
    ViewBag.Title = "Shop";
    Layout = "~/Views/Shared/_EStart.cshtml";

    var pro = new E_commerce.Models.Product();
}


<div class="container mt-5">
    <!-- Header Section -->
    <div class="text-center mb-5">
        <h1 class="display-4">Welcome to Our Shop</h1>
        <p class="lead">Find the best products curated just for you</p>
    </div>

    <form>
        @*<button type="button" id="allCategories" class="btn btn-outline-primary">All Categories</button>*@
        <a href="@Url.Action("Shop", "Products", new { id = "" })" class="btn btn-outline-primary">All Categories</a>


        @*<button type="button" id="Category1" class="btn btn-outline-primary">Donuts</button>*@
        <a href="@Url.Action("Shop", "Products", new { id = 1 })" class="btn btn-outline-primary">Donuts</a>


        @*<button type="button" id="Category2" class="btn btn-outline-primary">Cheesecake</button>*@
        <a href="@Url.Action("Shop", "Products", new { id = 2 })" class="btn btn-outline-primary">Cheesecake</a>


        @*<button type="button" id="Category3" class="btn btn-outline-primary">Pancake</button>*@
        <a href="@Url.Action("Shop", "Products", new { id = 3 })" class="btn btn-outline-primary">Pancake</a>

        <input type="hidden" name="selectedCategory" id="selectedCategory" value="all" />
    </form>
    <br />
    <br />
    <!-- Product Cards Section -->
    <div class="row">

        @foreach (var product in Model)
        {

            <div class="col-md-4 mb-4">
                <div class="card modern-card h-100">
                    <img src="@product.Image" class="card-img-top" alt="@product.ProductName">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title text-center">@product.ProductName</h5>
                        <p class="card-text text-center">@product.Description</p>
                        <p class="card-text text-center text-muted">$@product.Price</p>
                        <div class="mt-auto text-center">

                            <a href="@Url.Action("Details", "Products", new { id = product.ProductID })" class="btn btn-primary btn-modern">View Details</a>
                            @if (Session["name"] == "0")
                            {
                                <a href="@Url.Action("Create", "CartItems", new { id = product.ProductID, userId = Session["UserID"] })" class="btn btn-primary btn-modern">Add To Cart</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<!-- Optional: Add custom styling here -->
<style>
    .modern-card {
        border: none;
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease-in-out;
    }

        .modern-card:hover {
            transform: translateY(-10px);
        }

        .modern-card img {
            border-top-left-radius: 15px;
            border-top-right-radius: 15px;
        }

    .btn-modern {
        border-radius: 30px;
        padding: 10px 20px;
    }
</style>

<!-- Add this script reference if not already included -->
@section Scripts {
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
}






@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
            </td>
        </tr>
    }

    </table>*@